#!/usr/bin/python

import sys

from clone import do_clone
from pull import convert_in_place
from pull import do_pull

command_table = {
        "clone": do_clone,
        "checkout": do_clone,
        "co": do_clone,
        "pull": do_pull,
        "update": do_pull,
        }

def usage():
    print "Usage: cvc2git <command> <options>"

def main():
    if len(sys.argv) == 1:
        convert_in_place()
        return

    cmd = sys.argv[1]
    if cmd not in command_table:
        print "Error: unknow command %s" % cmd
        usage()
        return

    extra_args = sys.argv[2:]
    try:
        command_table[cmd](*extra_args)
    except TypeError: # FIXME this is likely to be affected by deeper calls
        print "Error: invalid arguments for command %s: %s" % (
                cmd, " ".join(extra_args))
        usage()

if __name__ == "__main__":
    main()
