#!/usr/bin/python

import sys

from clone import do_clone
from clone import in_place_convert
from pull import do_pull

command_table = {
        "clone": do_clone,
        "checkout": do_clone,
        "co": do_clone,
        "pull": do_pull,
        "update": do_pull,
        }

def usage():
    print "Usage: cvc2git <command> <options>"

def check_argv():
    if len(sys.argv) == 1:
        in_place_convert()
        sys.exit()

    if len(sys.argv) < 2:
        usage()
        sys.exit()

    if sys.argv[1] not in command_table:
        print "Error: unknow command %s" % sys.argv[1]
        usage()
        sys.exit()

def main():
    check_argv()
    command_table[sys.argv[1]](*sys.argv[2:])

if __name__ == "__main__":
    main()
