#!/bin/bash

cachedir="/tmp/fl2/tmp"
gitdir="/tmp/cvc2git"
branch="fl.2-devel"
label="foresight.rpath.org@fl:2-devel"

pushd $gitdir || exit 1
git checkout $branch || exit 1
popd

get-all-pkg-log $label $cachedir
cvc2git.py --history-dir=$cachedir/logs --git-dir=$gitdir
