#!/bin/bash

cachedir="/tmp/fl2/tmp"
gitdir="/tmp/cvc2git"
branch="fl.2-devel"
label="foresight.rpath.org@fl:2-devel"

pushd $gitdir || exit 1
git checkout $branch || exit 1
popd

./get-all-pkg-log --refresh $label $cachedir
cat $cachedir/sources-list | cut -d: -f1 | xargs ./cvc2git.py --history-dir=$cachedir/logs --git-dir=$gitdir --refresh
