#!/bin/bash

# Get all :source packages on a branch and fetch their 'cvc log' into a
# cachedir

usage() {
    echo "Usage:  $0 <label> <cachedir>"
    echo "    <label> is something like foresight.rpath.org@fl:2-devel"
    echo "    <cachedir> is the cache cachedir to store the :source package list and their 'cvc log' history"
    echo "Will reuse <cachedir> if it already exists."
    exit 1
}

if [ $# -ne 2 ]; then
    usage
fi

prefix="$(dirname $0)"
label="$1"
cachedir="$2"

fetch_history() {
    pkgs="$@"
    count="$#"
    i=1
    for x in $pkgs
    do
        pkgname=`echo $x | cut -d: -f1`
        printf "\33[2K\rfetching history of [%d/%d %d%%] %s..." $i $count $(($i * 100 / $count)) $pkgname
        $prefix/get-pkg-log $x > $cachedir/logs/$pkgname.log
        ((i+=1))
    done
    echo
}

mkdir -p $cachedir/logs
conary rq --labels --install-label $label | grep :source > $cachedir/sources-list.new

if [ ! -f $cachedir/sources-list ]; then
    pkgs=`cat $cachedir/sources-list.new`
else
    pkgs=$(diff -u $cachedir/sources-list $cachedir/sources-list.new |
           tail -n +3 | # remove the diff header
           grep "^+" | # only consider the + lines
           cut -b2- ) # remove the leading +
fi

mv -f $cachedir/sources-list.new $cachedir/sources-list

if [ -z "$pkgs" ]; then
    echo "Cache already up to date"
else
    fetch_history $pkgs
fi

exit 0
